jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      CSV_URL: ${{ secrets.CSV_DATA }}  # ✅ Pass the secret as an environment variable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug CSV_URL
        run: echo "CSV_URL is $CSV_URL"  # ✅ Check if CSV_URL is set

      - name: Run Python script
        run: python tb.py
