name: Run Python Script

on:
  push:
    branches:
      - main  # ✅ Runs when you push to the "main" branch
  pull_request:
    branches:
      - main  # ✅ Runs on pull requests to "main"
  workflow_dispatch:  # ✅ Allows you to run it manually from GitHub Actions

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      CSV_URL: ${{ secrets.CSV_DATA }}  # ✅ Pass the secret as an environment variable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
          pip install --upgrade pip
          pip install python-telegram-bot pandas gdown

      - name: Debug CSV_URL
        run: |
          echo "CSV_URL is: $CSV_URL"
          [[ -z "$CSV_URL" ]] && echo "⚠️ CSV_URL is empty!"

      - name: Run Python script
        run: python tb.py
